// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrKX5d_-4too-gsdvnha8knh_6uYybyi0',
    appId: '1:12513700806:android:c8e9d9048b318fa4b760c7',
    messagingSenderId: '12513700806',
    projectId: 'chat-test-c3fd9',
    storageBucket: 'chat-test-c3fd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqDYqGPAtX_E3GKmPValkSlo5UtjINU8Q',
    appId: '1:12513700806:ios:0aa3d6cf39131340b760c7',
    messagingSenderId: '12513700806',
    projectId: 'chat-test-c3fd9',
    storageBucket: 'chat-test-c3fd9.appspot.com',
    androidClientId: '12513700806-qj44q107r8mbqalubithqgmsdi3humd4.apps.googleusercontent.com',
    iosClientId: '12513700806-npva59do60sp29tthip06eaba9lirecn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
